chore: upgrade conventional commits
semantic-release/release-notes-generator pull request #640
Opened 2024-05-07 17:54 UTC by icco

This closes the following:

 - PRs: #632, #633, #634, #635, #636, #637, #638, #639
 - As suggested by https://github.com/conventional-changelog/conventional-changelog/issues/1267

2024-05-07 18:30 UTC, dededecline approved these changes

2024-05-07 22:40 UTC, travi commented
Please make sure our tests are passing. `npm test` should be enough to verify this locally.

2024-05-07 22:41 UTC, travi requested changes

2024-05-07 22:41 UTC, travi commented on package.json
> +    "conventional-changelog-jshint": "^5.0.0",
Please keep dev dependencies pinned to specific versions

2024-05-10 19:57 UTC, travi commented
> Please make sure our tests are passing. `npm test` should be enough to verify this locally.

@icco the tests continue to fail after your follow up to pin the dev dependencies. are you interested in working through the breaking changes related to these updates in order to help us move this forward?

2024-05-10 20:09 UTC, icco commented
> > Please make sure our tests are passing. `npm test` should be enough to verify this locally.
> 
> @icco the tests continue to fail after your follow up to pin the dev dependencies. are you interested in working through the breaking changes related to these updates in order to help us move this forward?

Yeah been trying to get the tests pass locally with no luck. I believe there's an underlying bug in the import plugin you use but can not figure it out.

2024-05-10 20:49 UTC, travi commented
appreciate the update and the investigation. we are starting to investigate as well, but unsure how much time we can dedicate soon. please feel free to keep us up to date if you make progress, even if that means pushing wip changes that dont get to a point of getting tests to a passing state.

it could also be helpful to start with running the integration tests (`npm run test:integration`) first for a larger scope feedback loop before getting distracted by the unit tests (`npm run test:unit`) if the interface changes are unclear.

2024-05-17 21:00 UTC, travi commented
appreciate the investment here, but closing in favor of https://github.com/semantic-release/release-notes-generator/pull/643. we could still use help updating the commit-analyzer plugin in similar ways in case you are still interested and the other PR helps with any complexities that you encountered with this effort

2024-05-17 21:00 UTC, closed without merging